window.resizeTo(900,600)
macro = "CODE:";
macro += "VERSION BUILD=9030808 RECORDER=FX\n";
macro += "SET !TIMEOUT 20\n";
macro += "wait seconds =1\n";
macro += "TAB T=OPEN\n";
macro += "TAB T=2\n";
macro += "TAB CLOSEALLOTHERS\n";
macro += "CLEAR\n";
macro += "SET !ERRORIGNORE YES\n";
macro += "SET !REPLAYSPEED fast\n";
macro += "SET !EXTRACT_TEST_POPUP NO\n";
macro += "wait seconds =1\n";
macro += "URL GOTO = https://bananominer.arikado.ru/?address=ban_3sqdn19on31w7d7g9iw7h8btamnk1fm9e5pmc9uhzgbe43kryg85iqk5b4za\n";
macro += "wait seconds =1\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "wait seconds =0.3\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "wait seconds =0.3\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "wait seconds =0.3\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "wait seconds =0.3\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "wait seconds =0.3\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "wait seconds =0.3\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "URL GOTO = javascript:web_increase_threads()\n";
macro += "wait seconds =1\n";
macro += "URL GOTO = javascript:web_client.start()\n";
macro += "URL GOTO = javascript:web_client.start()\n";
macro += "URL GOTO = javascript:web_client.start()\n";
macro += "URL GOTO = javascript:web_client.start()\n";
macro += "URL GOTO = javascript:web_client.start()\n";
macro += "wait seconds =1\n";
iimPlay(macro);
